sudo: required
language: java
jdk: oraclejdk8

services:
  - mysql

addons:
  sonarcloud:
  organization: vukovic98
  token: $SONAR_TOKEN

script:
  - cd team16
  - ./mvnw clean install
  - ./mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=vukovic98 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

dist: trusty

deploy:
  provider: heroku
  api_key: $API_KEY
  app: div-center